# Basic Phyton Programming
Description : This script is going to show you how to learn phyton from the beginning 
<br> Author : Eko Budi Prasetyo
<br> Date : 30 September 2019
<br> Source : [google](https://google.com/)
<br> Source : [google](https://google.com/"google")

* * *

* * * * *

* session1 : introduction
    * Arithmatics
    * methids
    * variabel
    * function
    * loop
* session2 : pandas and numpy
    * pandas
    * numpy
        * session 3 : data cleansing
            ** drop duplicates
            ** adding missing data

![img1](phyton.ico)

__test__
<br> **test**
<br> _test_
<br> *test*
<br> *Super*emphasis
<br> **Super**test

In [5]:
print("hello world")

hello world

In [6]:
print(2+5)

7

In [7]:
apel = 5
jeruk = 7

print(apel)
print(jeruk)
print(apel+jeruk)

5
7
12

In [12]:
print(True)
print(type(True))
print(type('True'))
print(type(False))

print(10==10)
print(5==6)
t = True
f = False
print(t or f)
print(t and f)
print(type(t))

True
<class 'bool'>
<class 'str'>
<class 'bool'>
True
False
True
False
<class 'bool'>

In [14]:
Fam = [2,3,4,5,6,7]
print(Fam)
type(Fam)
# List inside list
Data = [["Bob",160],["Charlie",150],["Brian",140.5]]

[2, 3, 4, 5, 6, 7]

In [15]:
# Built-In
print(Fam)
print(max(Fam))
print(min(Fam))
print(len(Fam))
# User Defined
print(Data)
x,y = max(Data, key=lambda a: a[1])
print(x)
print(y)

[2, 3, 4, 5, 6, 7]
7
2
6
[['Bob', 160], ['Charlie', 150], ['Brian', 140.5]]
Bob
160

In [3]:
name = "hello world33"
print(name)
print(type(name))
# "hello world" type is string
# Some Methods specifically
# associated with string type object are
print(name.capitalize())
print(name.upper())
print(name.lower())
print(name.strip("3"))

hello world33
<class 'str'>
Hello world33
HELLO WORLD33
hello world33
hello world

In [4]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)
    nums = [0, 1, 2, 3, 4]
    squares = [x ** 2 for x in nums]
    print(squares)

cat
[0, 1, 4, 9, 16]
dog
[0, 1, 4, 9, 16]
monkey
[0, 1, 4, 9, 16]

In [5]:
a=10
b=20
if a == b:
    print('yes')
else:
    print('no')

no

In [9]:
import sys
'numpy' in sys.modules

False

In [17]:
# Install and import
import numpy as np
Data = [["Bob",160],["Charlie",150],["Brian",140.5]]
height_list = [row[1] for row in Data]
print(type(height_list))
height_array = np.array(height_list)

print(height_array)
print(type(height_array))

<class 'list'>
[160.  150.  140.5]
<class 'numpy.ndarray'>

In [24]:
countries = ['spain', 'france', 'germany', 'norway']
capitals = ['madrid', 'paris', 'berlin', 'oslo']
ind_ger = countries.index('germany')
print(capitals[ind_ger])
europe = {'spain':'madrid', 'france':'paris','germany':'berlin', 'norway':'oslo'}

print(europe)
print(europe.keys())
print(europe.values())

type(europe)

berlin
{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo'}
dict_keys(['spain', 'france', 'germany', 'norway'])
dict_values(['madrid', 'paris', 'berlin', 'oslo'])

dict

In [3]:
import pandas as pd

In [4]:
pd.read_csv("test.csv")

    no  nama
0    1   asd
1    2   asd
2    3   asd
3    4  erte
4    5  erte
5    6   tyu
6    7   yui
7    8   we5
8    9   sdf
9   10   yui
10  11   yui
11  12   yui
12  13   yui
13  14   yui
14  15   yui
15  16   yui
16  17   yui

In [5]:
imdb = pd.read_csv("https://raw.githubusercontent.com/scalabretta/GroupProject--IMDB/master/Dataset/IMDB-database-update.csv",encoding='latin1')

In [6]:
imdb.shape

(3781, 36)

In [7]:
imdb.dtypes

movie_ID                       int64
movie_title                   object
duration                       int64
color                          int64
title_year                     int64
country                       object
language                      object
content_rating                object
budget_USD                     int64
gross_USD                      int64
net_USD                        int64
profitable                     int64
director_name                 object
director_top20?               object
director_facebook?             int64
director_facebook_likes        int64
actor_1_name                  object
actor_top20?                   int64
actor_1_facebook?              int64
actor_1_facebook_likes         int64
actor_2_name                  object
actor_top20?.1                 int64
actor_2_facebook?              int64
actor_2_facebook_likes         int64
actor_3_name                  object
actor_top20?.2                 int64
actor_3_facebook?              int64
actor_3_facebook_likes         int64
cast_total_facebook_likes      int64
movie_facebook?                int64
movie_facebook_likes;          int64
facenumber_in_poster           int64
num_voted_users                int64
num_user_for_reviews           int64
imdb_score                   float64
imdb_top_250                   int64
dtype: object

In [9]:
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3781 entries, 0 to 3780
Data columns (total 36 columns):
movie_ID                     3781 non-null int64
movie_title                  3781 non-null object
duration                     3781 non-null int64
color                        3781 non-null int64
title_year                   3781 non-null int64
country                      3781 non-null object
language                     3781 non-null object
content_rating               3781 non-null object
budget_USD                   3781 non-null int64
gross_USD                    3781 non-null int64
net_USD                      3781 non-null int64
profitable                   3781 non-null int64
director_name                3781 non-null object
director_top20?              3781 non-null object
director_facebook?           3781 non-null int64
director_facebook_likes      3781 non-null int64
actor_1_name                 3781 non-null object
actor_top20?                 3781 non-null int64
actor_1_facebook?            3781 non-null int64
actor_1_facebook_likes       3781 non-null int64
actor_2_name                 3781 non-null object
actor_top20?.1               3781 non-null int64
actor_2_facebook?            3781 non-null int64
actor_2_facebook_likes       3781 non-null int64
actor_3_name                 3781 non-null object
actor_top20?.2               3781 non-null int64
actor_3_facebook?            3781 non-null int64
actor_3_facebook_likes       3781 non-null int64
cast_total_facebook_likes    3781 non-null int64
movie_facebook?              3781 non-null int64
movie_facebook_likes;        3781 non-null int64
facenumber_in_poster         3781 non-null int64
num_voted_users              3781 non-null int64
num_user_for_reviews         3781 non-null int64
imdb_score                   3781 non-null float64
imdb_top_250                 3781 non-null int64
dtypes: float64(1), int64(26), object(9)
memory usage: 1.0+ MB

In [11]:
imdb.head(10)

,movie_ID,movie_title,duration,color,title_year,country,language,content_rating,budget_USD,gross_USD,...,actor_3_facebook?,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250
0,1,Avatar,178,1,2009,USA,English,PG-13,237000000,760505847,...,1,855,4834,1,33000,0,886204,3054,7.9,0
1,2,Pirates of the Caribbean: At World's End,169,1,2007,USA,English,PG-13,300000000,309404152,...,1,1000,48350,0,0,0,471220,1238,7.1,0
2,3,The Dark Knight Rises,164,1,2012,USA,English,PG-13,250000000,448130642,...,1,23000,106759,1,164000,0,1144337,2701,8.5,1
3,4,Spider-Man 3,156,1,2007,USA,English,PG-13,258000000,336530303,...,1,4000,46055,0,0,0,383056,1902,6.2,0
4,5,Batman v Superman: Dawn of Justice,183,1,2016,USA,English,PG-13,250000000,330249062,...,1,2000,24450,1,197000,0,371639,3018,6.9,0
5,6,Superman Returns,169,1,2006,USA,English,PG-13,209000000,200069408,...,1,903,29991,0,0,0,240396,2367,6.1,0
6,7,Man of Steel,143,1,2013,USA,English,PG-13,225000000,291021565,...,1,748,20495,1,118000,0,548573,2536,7.2,0
7,8,The Hobbit: The Battle of the Five Armies,164,1,2014,New Zealand,English,PG-13,250000000,255108370,...,1,773,9152,1,65000,0,354228,802,7.5,0
8,9,The Amazing Spider-Man,153,1,2012,USA,English,PG-13,230000000,262030663,...,1,963,28489,1,56000,0,451803,1225,7.0,0
9,10,Robin Hood,156,1,2010,USA,English,PG-13,200000000,105219735,...,1,738,3244,1,17000,0,211765,546,6.7,0

In [12]:
imdb.tail(5)

,movie_ID,movie_title,duration,color,title_year,country,language,content_rating,budget_USD,gross_USD,...,actor_3_facebook?,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250
3776,3777,New Year's Eve,113,1,2011,USA,English,PG-13,56000000,54540525,...,1,307,23456,1,20000,15,66579,134,5.7,0
3777,3778,Boogie Nights,155,1,1997,USA,English,R,15000000,26384919,...,1,170,3677,0,0,15,189032,560,7.9,0
3778,3779,Battle of the Year,110,1,2013,USA,English,PG-13,20000000,8888355,...,1,826,3177,0,0,19,7894,25,5.0,0
3779,3780,The Master,144,1,2012,USA,English,R,32000000,16377274,...,1,15,427,1,27000,31,105144,405,7.1,0
3780,3781,500 Days of Summer,95,1,2009,USA,English,PG-13,7500000,32391374,...,1,11000,54075,1,40000,43,376600,494,7.7,0

In [14]:
imdb.describe()

,movie_ID,duration,color,title_year,budget_USD,gross_USD,net_USD,profitable,director_facebook?,director_facebook_likes,...,actor_3_facebook?,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250
count,3781.000000,3781.000000,3781.000000,3781.000000,3.781000e+03,3.781000e+03,3.781000e+03,3781.000000,3781.000000,3781.000000,...,3781.000000,3781.000000,3781.000000,3781.000000,3781.000000,3781.000000,3.781000e+03,3781.000000,3781.000000,3781.000000
mean,1891.000000,109.950278,0.967204,2003.081989,4.572770e+07,5.182002e+07,6.092318e+06,0.531870,0.828352,801.610685,...,0.992066,764.333774,11417.335625,0.539011,9264.147051,1.378736,1.039808e+05,331.862470,6.457339,0.041523
std,1091.625012,22.299267,0.178125,9.837954,2.252895e+08,7.003776e+07,2.291199e+08,0.499049,0.377124,3058.757162,...,0.088733,1885.768343,19071.218619,0.498542,21398.159089,2.044844,1.513586e+05,410.112422,1.056270,0.199524
min,1.000000,37.000000,0.000000,1927.000000,2.180000e+02,1.620000e+02,-1.221330e+10,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.200000e+01,1.000000,1.600000,0.000000
25%,946.000000,95.000000,1.000000,1999.000000,1.000000e+07,7.605668e+06,-1.043974e+07,0.000000,1.000000,10.000000,...,1.000000,191.000000,1889.000000,0.000000,0.000000,0.000000,1.831000e+04,105.000000,5.900000,0.000000
50%,1891.000000,106.000000,1.000000,2005.000000,2.500000e+07,2.896520e+07,1.161099e+06,1.000000,1.000000,61.000000,...,1.000000,433.000000,3969.000000,1.000000,217.000000,1.000000,5.250900e+04,207.000000,6.600000,0.000000
75%,2836.000000,120.000000,1.000000,2010.000000,5.000000e+07,6.600997e+07,2.507490e+07,1.000000,1.000000,234.000000,...,1.000000,690.000000,16179.000000,1.000000,11000.000000,2.000000,1.263570e+05,394.000000,7.200000,0.000000
max,3781.000000,325.000000,1.000000,2016.000000,1.221550e+10,7.605058e+08,5.235058e+08,1.000000,1.000000,23000.000000,...,1.000000,23000.000000,656730.000000,1.000000,349000.000000,43.000000,1.689764e+06,5060.000000,9.300000,1.000000

In [15]:
imdb.isnull()

,movie_ID,movie_title,duration,color,title_year,country,language,content_rating,budget_USD,gross_USD,...,actor_3_facebook?,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3751,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3752,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3753,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3754,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3755,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3756,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3757,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3758,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3759,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3760,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3761,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3762,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3763,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3764,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3765,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3766,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3767,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3768,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3769,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3770,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3771,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3772,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3773,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3774,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3775,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3776,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3777,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3778,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3779,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3780,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [16]:
imdb[["duration", "gross_USD"]].describe()

          duration     gross_USD
count  3781.000000  3.781000e+03
mean    109.950278  5.182002e+07
std      22.299267  7.003776e+07
min      37.000000  1.620000e+02
25%      95.000000  7.605668e+06
50%     106.000000  2.896520e+07
75%     120.000000  6.600997e+07
max     325.000000  7.605058e+08

In [18]:
imdb["language"].value_counts().head(10)

English       3628
French          33
Spanish         23
Mandarin        14
German          10
Japanese        10
Cantonese        7
Italian          5
Hindi            5
Portuguese       5
Name: language, dtype: int64

In [21]:
import numpy as np

In [22]:
imdb["score_group"] = np.where(imdb["imdb_score"]>7.5,"high","low")

In [23]:
imdb["score_group"].value_counts()

low     3247
high     534
Name: score_group, dtype: int64

In [24]:
imdb.head()

,movie_ID,movie_title,duration,color,title_year,country,language,content_rating,budget_USD,gross_USD,...,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250,score_group
0,1,Avatar,178,1,2009,USA,English,PG-13,237000000,760505847,...,855,4834,1,33000,0,886204,3054,7.9,0,high
1,2,Pirates of the Caribbean: At World's End,169,1,2007,USA,English,PG-13,300000000,309404152,...,1000,48350,0,0,0,471220,1238,7.1,0,low
2,3,The Dark Knight Rises,164,1,2012,USA,English,PG-13,250000000,448130642,...,23000,106759,1,164000,0,1144337,2701,8.5,1,high
3,4,Spider-Man 3,156,1,2007,USA,English,PG-13,258000000,336530303,...,4000,46055,0,0,0,383056,1902,6.2,0,low
4,5,Batman v Superman: Dawn of Justice,183,1,2016,USA,English,PG-13,250000000,330249062,...,2000,24450,1,197000,0,371639,3018,6.9,0,low